# Golang CircleCI 2.0 configuration file
# See https://circleci.com/docs/2.0/language-go/
version: 2.1
jobs:
  build:
    working_directory: /home/circleci/zigmod
    docker:
      - image: alpine:edge
    steps:
      - checkout

      - run: apk add go
      - run: go version
      - run: go env
      - run: go get -v .
      - run: go test -v .
      - run: ./build_all.sh
      - store_artifacts:
          path: ./bin/
          destination: /artifacts/
      - run: ./make_release.sh
