# Golang CircleCI 2.0 configuration file
# See https://circleci.com/docs/2.0/language-go/
version: 2.1
jobs:
  build:
    working_directory: /home/circleci/zigmod
    docker:
      - image: golang
    environment:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - run: apt update
      - run: apt -y upgrade
      - checkout
      - run: git submodule update --init --recursive

      - run: apt -y install xz-utils jq
      - run: ./download_zig.sh 0.9.0-dev.794+65208a7fa
      - run: zig version
      - run: zig env
      - run: zig build -Dbootstrap
      - run: ./zig-out/bin/zigmod ci
      - run: zig build
      - run: ./build_all_zig.sh
      - run: rm ./zig-out/bin/zigmod
      - store_artifacts:
          path: ./zig-out/bin/
          destination: /artifacts/

      - run: mkdir -p /artifacts/
      - run: cp -R ./zig-out/bin/. /artifacts/
      - run: ./make_release.sh
